(OK) Loading cuda 10.2.89
(OK) Loading gcc system-default
Traceback (most recent call last):
  File "train.py", line 201, in <module>
    main()
  File "train.py", line 171, in main
    args=args
  File "train.py", line 55, in train
    for i, (images, target) in enumerate(train_loader):
  File "/home/rs619065/miniconda3/envs/kaggle/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/rs619065/miniconda3/envs/kaggle/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/home/rs619065/miniconda3/envs/kaggle/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/rs619065/miniconda3/envs/kaggle/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 14.
Original Traceback (most recent call last):
  File "/home/rs619065/miniconda3/envs/kaggle/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/rs619065/miniconda3/envs/kaggle/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rs619065/miniconda3/envs/kaggle/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/rwthfs/rz/cluster/home/rs619065/kaggle/PANDA/src/datasets.py", line 29, in __getitem__
    image = skimage.io.imread(file_path)
  File "/home/rs619065/miniconda3/envs/kaggle/lib/python3.6/site-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/rs619065/miniconda3/envs/kaggle/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "/home/rs619065/miniconda3/envs/kaggle/lib/python3.6/site-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/home/rs619065/miniconda3/envs/kaggle/lib/python3.6/site-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/home/rs619065/miniconda3/envs/kaggle/lib/python3.6/site-packages/imageio/core/functions.py", line 172, in get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "/home/rs619065/miniconda3/envs/kaggle/lib/python3.6/site-packages/imageio/core/request.py", line 121, in __init__
    self._parse_uri(uri)
  File "/home/rs619065/miniconda3/envs/kaggle/lib/python3.6/site-packages/imageio/core/request.py", line 257, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/hpcwork/rs619065/kaggle/prostate-cancer-grade-assessment/tissue_detection_train_images/3790f55cad63053e956fb73027179707.png'

